---
version: "3.6"
services:
  testfw:
    build: {context: "."}
    image: corpusops/ms_iptables
    cap_add:
    - NET_ADMIN
    network_mode: "host"
    volumes:
    - "./hacking/testrules:/rules/"
    - "./docker-init.sh:/docker-init.sh"
